### ISSUE TITLE
Jag fattar inte

### ISSUE THREAD

**Issue by Ihaveosteoperosis** [veckanu/web#20]
Hej Jag förstår inte var man ser veckan vill jätte järna veta vilken vecka det är eftersom jag har en uppgift som min lärare gav mig som ska vara klar imorgon och jag är jättestressad ska man typ trycka nån stans eller vadå kan inte sånt hära
Tack
//Mårten

**Comment by bohemima** [comment]
http://vecka.nu

**Comment by Ihaveosteoperosis** [comment]
Asså jag fattar fortfarande inte vart är siffrorna. finns det typ inga youtube-tutorial för det här är det året som står där eller va

**Comment by Ihaveosteoperosis** [comment]
//Mårten

**Comment by bohemima** [comment]
troll undanbedes.
