### ISSUE TITLE
vecka.nu 2017

### ISSUE THREAD

**Issue by bohemima** [veckanu/web#25]
Ärende till för att spåna för 2017 års vecka.nu.

**Comment by mikaelengstrom** [comment]
En kul grej man skulle kunna göra istället för olika branches för olika veckor skulle kunna vara om man istället lät folk pusha in sitt egna tema i en mapp och så slumpar man ut teman varje sidladdning. Skulle vara lite roligare med variation.

**Comment by ghost** [comment]
@bohemima Så enkelt men endå så bra, nice, @mikaelengstrom låter som en bra idé också, kan göra något enkelt när jag kommer hem och sen testa sourcen.

**Comment by bohemima** [comment]
@mikaelengstrom Skulle kunna tänka mig att man har vanliga vecka.nu looken, men en liten diskret option i nedre hörnet där man kan få en slumpad "themed" version. Teman skickas in precis som du skriver i undermappar.

**Comment by swantzter** [comment]
@mikaelengstrom håller med @bohemima där, problemet med den varianten är ju dock att det blir svårt med veckospesifika teman, det skulle ju betyda att teman behövde vara mer generella...

Dessutom skulle jag gärna göra gh fork ribbonen lite mer diskret, t.ex genom att byta ut mot en länk, har man en diskret footer för att välja tema kan man ju även ha en knapp för github.

snabbt ihopslängt exempel:
![footer](http://i.imgur.com/ciATEMx.png)

om man vill kan man även göra texten lite responsiv (även om det troligen inte behövs) t.ex:
```css
time {
    font-size: 40vw;
}
```

**Comment by bohemima** [comment]
@svbeon nu när vecka.nu har kört med GH ribonnen ett år kan den förminskas något, är inte helt hundra på vad/om vi hittar på något nytt med siten under nästa år - kanske fortsätter med vecko-branches ändå..

**Comment by swantzter** [comment]
Ja det vet man ju aldrig hur det blir - men det var bara ett förslag att flytta ner github länken i hörnet hur som för att få det lite mer diskret

**Comment by sandstrand** [comment]
Diskretare länk håller jag med om skulle vara att föredra.

Till min feature request:

### Dynamisk meta image 
Jag delade just vecka.nu i en facebooktråd om user experience och det gjorde mig uppmärksammad på att det inte finns någon meta image för sidan, och således ingen thumbnail vid delning. 

En png bör kunna genereras, per request eller schemalagt varje vecka, som visar aktuell vecka med design från sidan. Detta skulle ytterligare göra sidan användarvänlig utanför sin egen domän.

**Comment by bohemima** [comment]
@sandstrand angående dynamisk meta image så är detta implementerat sedan igår, lite experimentellt än så länge.
