### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by erdtman** [veckanu/web#28]
Not sure it is meaning full but I was wondering if there is a API that powers the page. 

I would like to do curl and get a number of JSON back.

**Comment by widarlein** [comment]
Just send a GET request to http://vecka.nu and set the **Accept** header to _application/json_ 

`curl --header "Accept: application/json" vecka.nu`

`{
  "week": 22
}`

**Comment by bohemima** [comment]
Hey, as @widarlein suggested you can simply set the Accept header to application/json (or text/xml or text/plain)

You can also do a HEAD request for / and fetch the X-Week-Number header.

**Comment by erdtman** [comment]
Got the answer from @widarlein 
`
curl -H "Accept: application/json" vecka.nu
`
or to only get the week number
`
curl -H "Accept: application/json" vecka.nu | jq [.week][0]
`

**Comment by erdtman** [comment]
Thanks!
