### ISSUE TITLE
Random "bra" bild från http://www.mapillary.com

### ISSUE THREAD

**Issue by gyllen** [veckanu/web#8]
Använder er sida varje måndag :)

Om jag skulle göra en vecka med random bild från Mapillary, skulle ni se det som för mycket reklam då?

Alla våra bilder är CC-BY-SA

**Comment by bohemima** [comment]
Hej, ledsen för sent svar, vecka.nu är i USA och promotar användningen av veckonummer, svårsålt...

Så länge det inte tar över för mycket av sidan och veckonummer fortfarande står i fokus med vecka.nu's färger så kan jag tycka att det är ok. Så skicka en PR så tar vi en titt!
